Repository Umc8th-Snack/Front-end, pull requests merged in 2025-07, with the labels that each got.

#14 [Chore] 라우팅, 절대 경로 설정
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/layout/MainLayout.tsx
  src/main.tsx
  src/pages/article/index.tsx
  src/pages/home/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/routes/ErrorBoundary.tsx
  src/routes/LoadingFallback.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/index.tsx
  src/routes/routeTypes.ts
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️ Setting, 경호

#39 [Chore] actions 정상 작동 확인
  src/pages/home/HomePage.tsx
Labels: ⚙️ Setting, 민재

#69 [Feat] 간추린 뉴스 박스 UI 구현
  src/pages/home/HomePage.tsx
  src/shared/assets/Bookmark.svg
  src/shared/assets/Rectangle105.svg
  src/shared/assets/Share.svg
  src/shared/components/SummarizedNewsContainer/SummarizedNewsContainer.tsx
Labels: 💫 Feature, 민재

#76 [Feat] 캐러셀 컨테이너 구현
  package.json
  pnpm-lock.yaml
  src/pages/home/HomePage.tsx
  src/shared/assets/left-arrow-active.svg
  src/shared/assets/left-arrow-inactive.svg
  src/shared/assets/right-arrow-active.svg
  src/shared/assets/right-arrow-inactive.svg
  src/shared/components/OnboardingCard/OnboardingCard.tsx
Labels: 💫 Feature, 민재

#79 [Feat] 메모장 컴포넌트 구현
  src/pages/home/HomePage.tsx
  src/shared/components/MemoPad/MemoPad.tsx
Labels: 💫 Feature, 민재

#57 [Feat] TodayGreetingBanner UI 구현
  src/shared/assets/calendar-icon.svg
  src/shared/assets/spring-dots.svg
  src/shared/components/TodayGreetingBanner.tsx
Labels: 💫 Feature, 서정

#51 [Feat] develop 기반 ArticleCard 구현
  src/shared/components/ArticleCard/ArticleCard.tsx
Labels: 💫 Feature, 수빈

#91 [Chore] shared/components 폴더 구조 정리
  src/shared/components/ToggleSwitch.tsx
  src/shared/components/banner/TodayGreetingBanner/TodayGreetingBanner/TodayGreetingBanner.tsx
  src/shared/components/box/InputBox/InputBox.tsx
  src/shared/components/modal/ConsentModal/ConsentModal.tsx
  src/shared/components/modal/DeleteAccountModal/DeleteAccountModal.tsx
  src/shared/components/modal/QuizCompleteModal/QuizCompleteModal.tsx
  src/shared/components/modal/QuizExitModal/QuizExitModal.tsx
  src/shared/components/modal/ShareModal/CircleShareButton.tsx
  src/shared/components/modal/ShareModal/CopyLinkBox.tsx
  src/shared/components/modal/ShareModal/ShareModal.tsx
  src/shared/components/modal/ShareModal/ShareToast.tsx
Labels: ⚙️ Setting, 서정
