Repository Umc8th-Snack/Front-end, pull requests merged in 2025-08, with the labels that each got.

#89 [Feat] 마이페이지&설정 뷰 퍼블리싱
  src/layout/MainLayout.tsx
  src/pages/delete-account/DeleteAccountPage.tsx
  src/pages/my/DummyData/DummyMemos.ts
  src/pages/my/DummyData/DummyScraps.ts
  src/pages/my/EditProfilePage.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/assets/default-image.svg
  src/pages/my/assets/left-pagination-active.svg
  src/pages/my/assets/left-pagination-inactive.svg
  src/pages/my/assets/right-pagination-active.svg
  src/pages/my/assets/right-pagination-inactive.svg
  src/pages/my/components/MemoCard.tsx
  src/pages/my/components/Pagination.tsx
  src/pages/my/components/Profile.tsx
  src/pages/my/components/ScrapCard.tsx
  src/pages/my/components/TabMenu.tsx
  src/pages/my/types/types.ts
  src/pages/password-change/.gitkeep
  src/pages/password-change/PasswordChangePage.tsx
  src/pages/settings/.gitkeep
  src/pages/settings/DeleteAccountPage.tsx
  src/pages/settings/EmailChangePage.tsx
  src/pages/settings/PasswordChangePage.tsx
  src/routes/index.tsx
  src/routes/routeTypes.ts
  src/shared/assets/icons/arrow-up-right.svg
  src/shared/components/Navbar/Navbar.tsx
  src/shared/components/modal/DeleteAccountModal/DeleteAccountModal.tsx
  src/shared/components/modal/SettingsDropdown/SettingsDropdown.tsx
  src/shared/components/modal/SettingsDropdown/settingsData.ts
Labels: 💫 Feature, 민재

#99 [Feat] 퀴즈 해설 뷰 퍼블리싱
  src/pages/test/QuizCommentaryPage.tsx
  src/routes/index.tsx
  src/shared/assets/icons/link.svg
  src/shared/components/chip/FieldChips.tsx
  src/shared/components/quiz/ArticleHeader.tsx
  src/shared/components/quiz/QuizCommentary.tsx
  src/shared/components/quiz/QuizResultMessage.tsx
  src/shared/components/quiz/QuizTestButtons.tsx
  src/shared/components/quiz/quizCommentaryData.ts
Labels: 💫 Feature, 수빈

#120 [Docs] Readme 수정
  README.md
Labels: 📄 Docs, 수빈

#125 [Fix] 메모패드 조회 및 저장 오류 해결
  src/pages/article/apis/memoApi.ts
  src/shared/components/modal/MemoPad/MemoPad.tsx
Labels: 🔧 Fix, 수빈

#136 [Feat] 파비콘 추가
  index.html
  public/favicon.png
Labels: 💫 Feature, 서정

#134 [Fix] 공유 불가능 기사 에러 처리
  src/shared/apis/shareApi.ts
  src/shared/components/modal/ShareModal/ShareModal.tsx
Labels: 🔧 Fix, 서정

#135 [Fix] 간추린 뉴스 mock data 삭제
  src/pages/article/ArticlePage.tsx
Labels: 🔧 Fix, 서정

#155 [Feat] 검색어 히스토리 드롭다운 구현
  src/pages/search/apis/searchHistoryApi.ts
  src/pages/search/components/SearchDropdown.tsx
  src/pages/search/hooks/useSearchHistory.ts
  src/pages/search/types/searchTypes.ts
  src/shared/components/Navbar/SearchBar.tsx
Labels: 💫 Feature, 서정

#157 [Style] 공유 페이지 반응형 UI 구현
  src/pages/article/SharePage.tsx
  src/shared/components/banner/TodayGreetingBanner/TodayGreetingBanner/TodayGreetingBanner.tsx
  src/shared/components/modal/loginModal/EmailLoginForm.tsx
  src/shared/components/modal/loginModal/LoginModal.tsx
  src/shared/components/modal/loginModal/SocialLoginButton.tsx
Labels: 🎨 Style, 서정

#181 [Style] 이메일/비밀번호 변경 & 회원탈퇴 페이지 반응형 ui 구현
  src/pages/settings/DeleteAccountPage.tsx
  src/pages/settings/EmailChangePage.tsx
  src/pages/settings/PasswordChangePage.tsx
  src/pages/settings/components/DeleteAccountModal/DeleteAccountModal.tsx
Labels: 🎨 Style, 민재
